name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
      
      - name: Build & push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with: 
          image: renzzzoup/clinicarodriguez-frontend-image
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    deploy:
    - name: Deploy to VPS via ssh
      uses: appleboy/ssh-actions@v1.5.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          cd /apps/frontend
          echo "Pulling new image..."
          docker compose pull
          echo "Bringing up containers..."
          docker compose up -d